name = "chmod"
description = "Change file mode bits"

[[options]]
short = "-R"
long = "--recursive"
description = "Change files and directories recursively"

[[options]]
short = "-v"
long = "--verbose"
description = "Output a diagnostic for every file processed"

[[options]]
short = "-c"
long = "--changes"
description = "Like verbose but report only when a change is made"

[[options]]
short = "-f"
long = "--silent"
description = "Suppress most error messages"

[[args]]
name = "mode"

[[args]]
name = "file"
template = "file_paths"
variadic = true
