name = "df"
description = "Report file system disk space usage"

[[options]]
short = "-h"
long = "--human-readable"
description = "Print sizes in human readable format"

[[options]]
short = "-T"
long = "--print-type"
description = "Print file system type"

[[options]]
short = "-i"
long = "--inodes"
description = "List inode information instead of block usage"

[[options]]
short = "-a"
long = "--all"
description = "Include pseudo file systems"

[[options]]
short = "-t"
long = "--type"
takes_arg = true
description = "Limit listing to file systems of given type"

[[options]]
short = "-x"
long = "--exclude-type"
takes_arg = true
description = "Exclude file systems of given type"

[[args]]
name = "file"
template = "file_paths"
variadic = true
