name = "mv"
description = "Move (rename) files"

[[options]]
short = "-n"
long = "--no-clobber"
description = "Do not overwrite an existing file"

[[options]]
short = "-v"
long = "--verbose"
description = "Explain what is being done"

[[options]]
short = "-i"
long = "--interactive"
description = "Prompt before overwrite"

[[options]]
short = "-f"
long = "--force"
description = "Do not prompt before overwriting"

[[options]]
short = "-u"
long = "--update"
description = "Move only when source is newer"

[[args]]
name = "source"
template = "file_paths"
variadic = true
