name = "yarn"
description = "JavaScript package manager"

[[subcommands]]
name = "add"
description = "Install a package"

  [[subcommands.options]]
  short = "-D"
  long = "--dev"
  description = "Save as devDependency"

  [[subcommands.options]]
  short = "-E"
  long = "--exact"
  description = "Install exact version"

  [[subcommands.options]]
  short = "-P"
  long = "--peer"
  description = "Save as peerDependency"

  [[subcommands.args]]
  name = "packages"
  variadic = true

[[subcommands]]
name = "remove"
description = "Remove a package"

  [[subcommands.args]]
  name = "packages"
  variadic = true

[[subcommands]]
name = "install"
description = "Install all dependencies"

  [[subcommands.options]]
  long = "--frozen-lockfile"
  description = "Don't generate a lockfile"

  [[subcommands.options]]
  long = "--ignore-engines"
  description = "Ignore engines check"

  [[subcommands.options]]
  long = "--production"
  description = "Install production dependencies only"

[[subcommands]]
name = "run"
description = "Run a defined package script"

  [[subcommands.args]]
  name = "script"
  [subcommands.args.generator]
  command = "node -e \"try{const p=require('./package.json');Object.keys(p.scripts||{}).forEach(s=>console.log(s))}catch(e){}\""
  cache_ttl_secs = 30

[[subcommands]]
name = "test"
description = "Run the test script"

[[subcommands]]
name = "build"
description = "Run the build script"

[[subcommands]]
name = "start"
description = "Run the start script"

[[subcommands]]
name = "init"
description = "Create a new package"

  [[subcommands.options]]
  short = "-y"
  long = "--yes"
  description = "Accept all defaults"

[[subcommands]]
name = "link"
description = "Symlink a package folder"

[[subcommands]]
name = "unlink"
description = "Remove a previously created symlink"

[[subcommands]]
name = "upgrade"
description = "Upgrade packages"

  [[subcommands.options]]
  long = "--latest"
  description = "Upgrade to the latest version"

  [[subcommands.args]]
  name = "packages"
  variadic = true

[[subcommands]]
name = "info"
description = "Show information about a package"

  [[subcommands.args]]
  name = "package"

[[subcommands]]
name = "why"
description = "Show why a package has been installed"

  [[subcommands.args]]
  name = "package"

[[subcommands]]
name = "global"
description = "Install packages globally"

  [[subcommands.subcommands]]
  name = "add"
  description = "Install a package globally"

    [[subcommands.subcommands.args]]
    name = "packages"
    variadic = true

  [[subcommands.subcommands]]
  name = "remove"
  description = "Remove a global package"

    [[subcommands.subcommands.args]]
    name = "packages"
    variadic = true

  [[subcommands.subcommands]]
  name = "list"
  description = "List global packages"

[[subcommands]]
name = "cache"
description = "Manage the yarn cache"

  [[subcommands.subcommands]]
  name = "clean"
  description = "Remove all cached packages"

  [[subcommands.subcommands]]
  name = "dir"
  description = "Print the cache directory path"

  [[subcommands.subcommands]]
  name = "list"
  description = "List cached packages"
